name: main
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * 0"
env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
jobs:
  main:
    runs-on: ubuntu-latest
    container: codecache/terraform:0.14.6
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: terraform init
      - name: apply
        run: terraform apply -auto-approve test
      - name: check
        run: terraform plan -detailed-exitcode test
      - name: destroy
        run: terraform destroy -auto-approve test
      - name: lint
        run: terraform fmt -recursive -check
